apps/dashboards/urls.py
from django.urls import path
from rest_framework import routers

from apps.projects.access import login_and_project_required

from . import frames, rest, views
from .access import (
    dashboard_is_password_protected,
    dashboard_is_public,
    login_and_dashboard_required,
    login_and_dashboardupdate_required,
    login_and_dashboardversion_required,
)

app_name = "dashboards"

urlpatterns = [
    # views
    path(
        "<hashid:pk>/name",
        login_and_dashboard_required(frames.DashboardName.as_view()),
        name="name",
    ),
    path(
        "<hashid:pk>/duplicate",
        login_and_dashboard_required(views.DashboardDuplicate.as_view()),
        name="duplicate",
    ),
    path(
        "<hashid:pk>/print",
        login_and_dashboard_required(views.DashboardPrint.as_view()),
        name="print",
    ),
    path(
        "<uuid:shared_id>",
        dashboard_is_public(views.DashboardPublic.as_view()),
        name="public",
    ),
    path(
        "<uuid:shared_id>/login",
        dashboard_is_password_protected(views.DashboardLogin.as_view()),
        name="login",
    ),
    path(
        "<uuid:shared_id>/logout",
        dashboard_is_password_protected(views.DashboardLogout.as_view()),
        name="logout",
    ),
    # frames
    path(
        "<hashid:pk>/share",
        login_and_dashboard_required(frames.DashboardShare.as_view()),
        name="share",
    ),
    path(
        "version/<hashid:pk>/restore",
        login_and_dashboardversion_required(views.DashboardRestore.as_view()),
        name="restore",
    ),
    path(
        "update/<hashid:pk>/restore",
        login_and_dashboardupdate_required(views.DashboardUpdateRestore.as_view()),
        name="restore-update",
    ),
    path(
        "version/<hashid:pk>/rename",
        login_and_dashboardversion_required(frames.DashboardVersionRename.as_view()),
        name="version-rename",
    ),
]

router = routers.DefaultRouter()
router.register("api/dashboards", rest.DashboardViewSet, basename="Dashboard")
urlpatterns += router.urls

project_urlpatterns = (
    [
        path(
            "", login_and_project_required(views.DashboardList.as_view()), name="list"
        ),
        path(
            "overview",
            login_and_project_required(frames.DashboardOverview.as_view()),
            name="overview",
        ),
        path(
            "new",
            login_and_project_required(views.DashboardCreate.as_view()),
            name="create",
        ),
        path(
            "create_from_integration",
            login_and_project_required(views.DashboardCreateFromIntegration.as_view()),
            name="create_from_integration",
        ),
        path(
            "<hashid:pk>",
            login_and_project_required(views.DashboardDetail.as_view()),
            name="detail",
        ),
        path(
            "<hashid:pk>/delete",
            login_and_project_required(views.DashboardDelete.as_view()),
            name="delete",
        ),
        path(
            "<hashid:dashboard_id>/pages/new",
            login_and_project_required(views.PageCreate.as_view()),
            name="page-create",
        ),
        path(
            "<hashid:dashboard_id>/pages/<hashid:pk>",
            login_and_project_required(views.PageDelete.as_view()),
            name="page-delete",
        ),
        path(
            "<hashid:dashboard_id>/pages/<hashid:pk>/move",
            login_and_project_required(views.PageMove.as_view()),
            name="page-move",
        ),
        # frames
        path(
            "<hashid:dashboard_id>/pages/<hashid:pk>/name",
            login_and_project_required(frames.DashboardPageName.as_view()),
            name="page-name",
        ),
        path(
            "<hashid:pk>/settings",
            login_and_project_required(frames.DashboardSettings.as_view()),
            name="settings",
        ),
        path(
            "<hashid:pk>/history",
            login_and_project_required(frames.DashboardHistory.as_view()),
            name="history",
        ),
    ],
    "project_dashboards",
)

apps/dashboards/widgets/urls.py
from django.urls import include, path

from . import views

app_name = "widgets"
urlpatterns = [
    path("", views.WidgetList.as_view(), name="list"),
    path("new", views.WidgetCreate.as_view(), name="create"),
    path("<int:pk>", views.WidgetDetail.as_view(), name="detail"),
    path("<int:pk>/update", views.WidgetUpdate.as_view(), name="update"),
    path("<int:pk>/delete", views.WidgetDelete.as_view(), name="delete"),
    path("<int:pk>/config", views.WidgetConfig.as_view(), name="config"),
    path("<int:pk>/output", views.WidgetOutput.as_view(), name="output"),
    path(
        "<int:widget_id>/filters/",
        include(
            "apps.dashboards.widgets.filters.urls",
            namespace="filters",
        ),
    ),
]

gyana/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, register_converter
from django.urls.converters import IntConverter
from rest_framework.documentation import get_schemajs_view, include_docs_urls

from apps.base.converters import HashIdConverter

register_converter(HashIdConverter if settings.USE_HASHIDS else IntConverter, "hashid")

from apps.controls import urls as control_urls
from apps.customapis import urls as api_urls
from apps.dashboards import urls as dashboard_urls
from apps.integrations import urls as integration_urls
from apps.invites import urls as invite_urls
from apps.nodes import urls as node_urls
from apps.oauth2 import urls as oauth2_urls
from apps.projects import urls as project_urls
from apps.sheets import urls as sheet_urls
from apps.teams import urls as team_urls
from apps.uploads import urls as upload_urls
from apps.users import urls as users_urls
from apps.widgets import urls as widget_urls
from apps.workflows import urls as workflow_urls

schemajs_view = get_schemajs_view(title="API")


integration_urlpatterns = [
    path("", include(integration_urls.project_urlpatterns)),
    path("customapis/", include(api_urls.integration_urlpatterns)),
    path("sheets/", include(sheet_urls.integration_urlpatterns)),
    path("uploads/", include(upload_urls.integration_urlpatterns)),
]

# urls that are scoped within a project
project_urlpatterns = [
    path("", include("apps.projects.urls")),
    path("<hashid:project_id>/integrations/", include(integration_urlpatterns)),
    path("<hashid:project_id>/workflows/", include(workflow_urls.project_urlpatterns)),
    path(
        "<hashid:project_id>/dashboards/", include(dashboard_urls.project_urlpatterns)
    ),
    path("<hashid:project_id>/oauth2/", include(oauth2_urls.project_urlpatterns)),
    path(
        "<hashid:project_id>/dashboards/<hashid:dashboard_id>/widgets/",
        include(widget_urls.dashboard_urlpatterns),
    ),
    path(
        "<hashid:project_id>/dashboards/<hashid:dashboard_id>/controls/",
        include(control_urls.dashboard_urlpatterns),
    ),
]


teams_urlpatterns = [
    path("", include("apps.teams.urls")),
    path("<hashid:team_id>/invites/", include(invite_urls.team_urlpatterns)),
    path("<hashid:team_id>/projects/", include(project_urls.team_urlpatterns)),
    path("<hashid:team_id>/members/", include(team_urls.membership_urlpatterns)),
]


urlpatterns = [
    path("admin_tools/", include("admin_tools.urls")),
    path("admin/", admin.site.urls),
    path("exports/", include("apps.exports.urls")),
    path("controls/", include("apps.controls.urls")),
    path("users/", include("apps.users.urls")),
    path("filters/", include("apps.filters.urls")),
    path("teams/", include(teams_urlpatterns)),
    path("projects/", include(project_urlpatterns)),
    path("integrations/", include("apps.integrations.urls")),
    path("workflows/", include("apps.workflows.urls")),
    path("workflows/<int:pk>/", include(node_urls.workflow_urlpatterns)),
    path("dashboards/", include("apps.dashboards.urls")),
    path("widgets/", include("apps.widgets.urls")),
    path("invitations/", include("invitations.urls")),
    path("nodes/", include("apps.nodes.urls")),
    path("uploads/", include("apps.uploads.urls")),
    path("sheets/", include("apps.sheets.urls")),
    path("oauth2/", include("apps.oauth2.urls")),
    path("tables/", include("apps.tables.urls")),
    path("", include("apps.web.urls")),
    path("fp/", include("django_drf_filepond.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    path("hijack/", include("hijack.urls", namespace="hijack")),
    # API docs
    # these are needed for schema.js
    path("docs/", include_docs_urls(title="API Docs")),
    path("schemajs/", schemajs_view, name="api_schemajs"),
    path("", include(users_urls.accounts_urlpatterns)),
]

if "silk" in settings.INSTALLED_APPS:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dashboards/widgets/filters/models.py
from apps.dashboards.widgets.models import Widget
from django.db import models


class Filter(models.Model):
    class Type(models.TextChoices):
        INTEGER = "INTEGER", "Integer"
        STRING = "STRING", "String"

    class IntegerPredicate(models.TextChoices):
        EQUAL = "equal", "is equal to"
        NEQUAL = "nequal", "is not equal to"

    class StringPredicate(models.TextChoices):
        STARTSWITH = "starts_with", "starts with"
        ENDSWITH = "ends_with", "ends with"

    widget = models.ForeignKey(Widget, on_delete=models.CASCADE)

    column = models.CharField(max_length=300)
    type = models.CharField(max_length=8, choices=Type.choices)

    integer_predicate = models.CharField(
        max_length=16, choices=IntegerPredicate.choices, null=True, blank=True
    )
    integer_value = models.BigIntegerField(null=True, blank=True)

    string_predicate = models.CharField(
        max_length=16, choices=StringPredicate.choices, null=True, blank=True
    )
    string_value = models.TextField(null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.column

apps/dashboards/widgets/filters/views.py
from apps.dashboards.mixins import DashboardMixin
from apps.dashboards.widgets.mixins import WidgetMixin
from django import forms
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import DeleteView
from lib.bigquery import get_columns
from turbo_response.views import TurboCreateView, TurboUpdateView

from .forms import get_filter_form
from .models import Filter


class FilterList(DashboardMixin, WidgetMixin, ListView):
    template_name = "filters/list.html"
    model = Filter
    paginate_by = 20


class FilterCreate(DashboardMixin, WidgetMixin, TurboCreateView):
    template_name = "filters/create.html"
    model = Filter

    @property
    def column(self):
        return self.request.GET.get("column")

    @property
    def column_type(self):
        schema = get_columns(self.widget.dataset)
        return [c.field_type for c in schema if c.name == self.column][0]

    def get_form_class(self):
        if self.column is not None:
            return get_filter_form(self.column_type)
        return get_filter_form()

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["columns"] = [(f.name, f.name) for f in get_columns(self.widget.dataset)]
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial["widget"] = self.widget
        for key in self.request.GET:
            initial[key] = self.request.GET[key]
        return initial

    def form_valid(self, form: forms.Form) -> HttpResponse:
        form.instance.type = self.column_type
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse(
            "dashboards:widgets:filters:list", args=(self.dashboard.id, self.widget.id)
        )


class FilterDetail(DashboardMixin, WidgetMixin, DetailView):
    template_name = "filters/detail.html"
    model = Filter


class FilterUpdate(DashboardMixin, WidgetMixin, TurboUpdateView):
    template_name = "filters/update.html"
    model = Filter

    @property
    def column_type(self):
        schema = get_columns(self.widget.dataset)
        return [c.field_type for c in schema if c.name == self.object.column][0]

    def get_form_class(self):
        return get_filter_form(self.object.type)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["columns"] = [(f.name, f.name) for f in get_columns(self.widget.dataset)]
        return kwargs

    def form_valid(self, form: forms.Form) -> HttpResponse:
        form.instance.type = self.column_type
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse(
            "dashboards:widgets:filters:update",
            args=(self.dashboard.id, self.widget.id, self.object.id),
        )


class FilterDelete(DashboardMixin, WidgetMixin, DeleteView):
    template_name = "filters/delete.html"
    model = Filter

    def get_success_url(self) -> str:
        return reverse(
            "dashboards:widgets:filters:list", args=(self.dashboard.id, self.widget.id)
        )

apps/dashboards/widgets/views.py
from apps.dashboards.mixins import DashboardMixin
from django.db.models.query import QuerySet
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import DeleteView
from lib.bigquery import get_columns, query_widget
from lib.chart import to_chart
from turbo_response.views import TurboCreateView, TurboUpdateView

from .forms import WidgetConfigForm, WidgetForm
from .models import Widget


class WidgetList(DashboardMixin, ListView):
    template_name = "widgets/list.html"
    model = Widget
    paginate_by = 20

    def get_queryset(self) -> QuerySet:
        return Widget.objects.filter(dashboard=self.dashboard).all()


class WidgetCreate(DashboardMixin, TurboCreateView):
    template_name = "widgets/create.html"
    model = Widget
    form_class = WidgetForm

    def get_initial(self):
        initial = super().get_initial()
        initial["dashboard"] = self.dashboard
        return initial

    def get_success_url(self) -> str:
        return reverse("dashboards:widgets:list", args=(self.dashboard.id,))


class WidgetDetail(DashboardMixin, DetailView):
    template_name = "widgets/detail.html"
    model = Widget


class WidgetUpdate(DashboardMixin, TurboUpdateView):
    template_name = "widgets/update.html"
    model = Widget
    form_class = WidgetForm

    def get_success_url(self) -> str:
        return reverse("dashboards:widgets:list", args=(self.dashboard.id,))


class WidgetDelete(DashboardMixin, DeleteView):
    template_name = "widgets/delete.html"
    model = Widget

    def get_success_url(self) -> str:
        return reverse("dashboards:widgets:list", args=(self.dashboard.id,))


# Turbo frames


class WidgetConfig(DashboardMixin, TurboUpdateView):
    template_name = "widgets/config.html"
    model = Widget
    form_class = WidgetConfigForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["columns"] = [(f.name, f.name) for f in get_columns(self.object.dataset)]
        return kwargs

    def get_success_url(self) -> str:
        return reverse(
            "dashboards:widgets:config", args=(self.dashboard.id, self.object.id)
        )


class WidgetOutput(DashboardMixin, DetailView):
    template_name = "widgets/output.html"
    model = Widget

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        df = query_widget(self.object)
        chart = to_chart(df, self.object)
        context_data["chart"] = chart.render()

        return context_data

apps/dashboards/templates/dashboards/_restore_cell.html
<form
  method="POST"
  class="form--no-layout"
  action="{% url href object.id %}"
  hx-target="body"
>
  {% csrf_token %}

  <button
    class="table__action"
    type="submit"
    x-tooltip="Restore current dashboard to this version"
  >
    <i class="fa fa-fw fa-undo"></i>
  </button>
</form>

apps/dashboards/templates/dashboards/create.html
<form method="post" action="{% url 'project_dashboards:create' project.id %}?mode=edit" class="form">
  {% csrf_token %}

  <input type="hidden" name="project" value="{{ project.id }}" />

  <button data-cy='dashboard-create' type="submit" class="button button--filled button--sm ml-4">
    <i class="fas fa-fw fa-plus"></i> New Dashboard
  </button>
</form>

apps/dashboards/templates/dashboards/delete.html
{% extends "projects/settings_base.html" %}

{% block app %}
  <div class="flex flex-1 flex-col justify-center items-center self-center max-w-xl">
    <h1 class="mb-3">Delete: {{ object.name }}</h1>
    <p class="alert mb-6">Are you sure you want to delete this? This action is <strong>irreversible</strong>.</p>

    <form
      action="{% url 'project_dashboards:delete' project.id object.id %}"
      class="w-full"
      method="post"
    >
      {% csrf_token %}

      <div class='flex gap-3 w-full'>
        <a
          href="{% url 'project_dashboards:detail' project.id object.id %}"
          class="button button--tertiary flex-1"
        >
          Go back
        </a>

        <button type="submit" class="button button--danger flex-1">Yes</button>
      </div>
    </form>
  </div>
{% endblock %}

apps/dashboards/templates/dashboards/detail.html
{% extends "projects/base.html" %}
{% load waffle_tags static %}

{% block app-class %}
  overflow-hidden
{% endblock app-class %}

{% block head.extra %}
  {% if dashboard.font_family %}
    <link
      href="https://fonts.googleapis.com/css2?family={{ dashboard.font_family.split|join:'+' }}:wght@400&display=swap"
      rel="stylesheet"
    />
  {% endif %}

  {% if font_families %}
    {% for id, font_family in font_families %}
      <link
        href="https://fonts.googleapis.com/css2?family={{ font_family.split|join:'+' }}&text={{ font_family.split|join:''|upper }}"
        rel="stylesheet"
      />
    {% endfor %}

    <style>
      {% for id, font_family in font_families %}
        option[value*="{{ font_family }}"] {
          font-family: "{{ font_family }}";
        }
      {% endfor %}
    </style>
  {% endif %}
{% endblock head.extra %}
{% block app %}
  <div class="dashboard__header">
    <div class="flex items-center gap-2 mr-auto">
      {% include "dashboards/name.html" %}

      <span class="bold">-</span>

      {% include "dashboards/forms/name_page.html" %}
    </div>

    {% if not request.GET.mode or request.GET.mode == "edit" %}
      <div x-data="popover({ placement: 'bottom-start', theme: 'popover-menu' })">
        <button
          x-ref="trigger"
          class="button button--sm button--tertiary"
        >
          More <i class="fas fa-angle-down"></i>
        </button>

        <template x-ref="body">
          <p
            class="list__item list__item--br w-full"
          >
            Dashboard
          </p>

          <form
            method="POST"
            action="{% url "dashboards:duplicate" object.id %}"
            class="form--no-layout"
          >
            {% csrf_token %}

            <button
              type="submit"
              class="list__item list__item--interactive w-full"
              id="dashboards-duplicate-{{ object.id }}"
              data-loading-false
            >
              Duplicate
            </button>
          </form>

          <a
            class="list__item list__item--interactive w-full"
            href="{% url "project_dashboards:delete" project.id object.id %}"
          >
            Delete
          </a>

          {% flag 'beta' %}
            <a
              class="list__item list__item--interactive w-full"
              href="{% url "dashboards:print" object.id %}"
            >
              <span class='beta mr-4'>Export as PDF</span>
            </a>
          {% endflag %}

          {% flag 'beta' %}
            <button
              x-modal.wide.tall="{% url "project_dashboards:history" project.id object.id %}?category=general"
              class="list__item list__item--interactive w-full"
            >
              <span class='beta mr-4'>History</span>
            </button>
          {% endflag %}

          <p
            class="list__item list__item--br w-full"
          >
            Page
          </p>

          <form
            method="POST"
            action="{% url "project_dashboards:page-create" project.id object.id %}"
            class="form--no-layout"
          >
            {% csrf_token %}

            <button
              type="submit"
              class="list__item list__item--interactive w-full"
              id="dashboards-add-page-{{ object.id }}"
              data-loading-false
            >
              Add new page
            </button>
          </form>

          <form
            method="POST"
            action="{% url "project_dashboards:page-delete" project.id object.id page.id %}"
            class="form--no-layout"
          >
            {% csrf_token %}

            <button
              type="submit"
              {% if page_count == 1 or page.position == 1 %}disabled{% endif %}
              class="list__item list__item--interactive w-full"
              id="dashboards-delete-page-{{ object.id }}"
              data-loading-false
            >
              Delete current page
            </button>
          </form>

          <div x-data="popover({ placement: 'right', theme: 'popover-menu' })">
            <button
              class="list__item list__item--interactive w-full"
              x-ref="trigger"
            >
              Move page to
            </button>

            <template x-ref="body">
              {% include 'dashboards/forms/move_page.html' %}
            </template>
          </div>
        </template>
      </div>


      <button class="button button--sm button--tertiary"
        x-tooltip="Customize dimensions, grid spacing and color palette"
        x-modal.wide.tall.reload="{% url "project_dashboards:settings" project.id object.id %}?category=general">
        <i class="fas fa-fw fa-paint-brush"></i> Theme and Layout
      </button>
    {% endif %}

    <div x-tooltip="Click to change view mode">
      {% if not request.GET.mode or request.GET.mode == "edit" %}
        <a href="?mode=view&dashboardPage={{ page.position }}"
          class="button button--sm button--tertiary">
          <i class="fas fa-fw fa-eye"></i> Preview
        </a>
      {% else %}
        <a href="?mode=edit&dashboardPage={{ page.position }}"
          class="button button--sm">
          <i class="fas fa-fw fa-pen"></i> Edit
        </a>
      {% endif %}
    </div>

    <button
      id="dashboard-share-{{ object.id }}"
      class="button button--sm button--success"
      x-tooltip="Share a public or password-protected link"
      x-modal="{% url "dashboards:share" object.id %}"
    >
      <i class="fas fa-fw fa-share"></i> Share
    </button>
  </div>

  <div class="w-full flex flex-row overflow-hidden">
    <div class="dashboard">
      {% include "dashboards/canvas.html" %}
      {% include "dashboards/page_controls.html" %}
    </div>

    {% if request.GET.mode != "view" %}
      <aside class="dashboard-sidebar">
        {% for category_id, category in categories %}
          <div class="pad collapsable-component" x-data="{ open: true }" :class="{ 'active': open }">
            <h3 class="cursor-pointer" @click="open = !open">
              {{ category }}
            </h3>
            <div class="collapsable flex flex-col max-h-0 overflow-hidden"
              :style="{ maxHeight: open ? $el.scrollHeight + 'px' : null }">
              <div class="flex flex-col gap-3 pt-4">
                {% for id, txt, icon, choice_category, verbose_name in choices %}
                  {% if choice_category|lower == category_id|lower %}
                    <div id="widget-{{ id }}"
                      class="dashboard-sidebar__item w-full cursor-draggable"
                      x-data
                      @dragstart="$event.dataTransfer.setData('application/gydashboard', '{{ id }}')
                        $event.dataTransfer.effectAllowed = 'move';"
                      draggable="true">
                      <i class="dashboard-sidebar__icon fas fa-fw fa-lg {{ icon }}"></i>
                      <p class="dashboard-sidebar__name">
                        {{ verbose_name }}
                      </p>
                      <i class="fas fa-fw fa-grip-vertical fa-sm text-black-10"></i>
                    </div>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
          <hr>
        {% endfor %}

        <div class="pad collapsable-component" x-data="{ open: true }" :class="{ 'active': open }">
          <h3 class="cursor-pointer" @click="open = !open">
            Controls
          </h3>

          {% include 'controls/create.html' %}
        </div>
      </aside>
    {% endif %}
  </div>
{% endblock %}

{% block body.javascript %}
  <!-- Include the Quill library -->
  <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
  <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

  <script src="{% static 'js/components-bundle.js' %}"></script>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

  <script src="{% static 'js/dashboards-bundle.js' %}"></script>
  <script src="{% static 'js/widgets-bundle.js' %}"></script>
{% endblock body.javascript %}

apps/dashboards/templates/dashboards/login.html
{% extends "dashboards/public.html" %}

{% block head %}
  <title>Password protected page</title>
{% endblock %}

{% block body %}
  <div class="flex flex-col m-auto justify-center items-center">
    <h2 class="mb-7">Password protected page</h2>

    <form
      class="w-full form--no-layout"
      method="post"
    >
      {% csrf_token %}

      {{ form }}

      <button
        class="button button-primary w-full mt-4"
        type="submit"
        hx-boost="false"
      >
        Submit
      </button>
    </form>
  </div>
{% endblock body %}

apps/dashboards/templates/dashboards/share.html
{% load help_utils crispy_forms_tags %}

<section class="flex flex-col h-full whitespace-normal">
  <div class="workflow-detail__header">
    <h3 class="mr-auto">Share</h3>

    <button class="modal__close">
      <i class="fal fa-times fa-lg"></i>
    </button>
  </div>

  <div class="pad">
    <div class="flex mb-3 justify-between items-center">
      <h2>
        {{ object.get_shared_status_display }}
      </h2>
      {% link_article "dashboards" "share" %}
    </div>

    <p class="mb-4">
      {% if object.shared_status == "private" %}
        This dashboard is currently <strong>private</strong>.
        Only members of your team can view and edit it.
      {% elif object.shared_status == "public" %}
        This dashboard is currently <strong>public</strong>.
        Everyone with the link below can view it.
      {% elif object.shared_status == "password_protected" %}
        This dashboard is currently <strong>password-protected</strong>.
        Everyone with the link below and your chosen password can view it.
      {% endif %}
    </p>

    {% if object.shared_status != "private" %}
      <div x-data class="clipboard-copy mb-4">
        <a
          href="{{ dashboard.public_url }}"
          target="_blank"
          rel="noreferrer noopener"
        >
          <pre x-ref="content">{{ dashboard.public_url }}</pre>
        </a>

        <button type="button"
          @click="navigator.clipboard.writeText($refs.content.innerText)">
          <i class="fa fa-clipboard"></i>
        </button>
      </div>
    {% endif %}

    <form
      id="dashboard-share-form"
      hx-post="{% url "dashboards:share" object.id %}"
    >
      {% csrf_token %}

      {% crispy form %}

      <button
        class="button button--success button--sm w-full"
        id="dashboard-share-update"
        name="submit"
        type="submit"
        value="Save & Preview"
      >
        Update
      </button>
    </form>

    {% if object.shared_status != "private" %}
      <div class="mt-7">
        <h3 class="mb-3">Embed code</h3>
        <p class="mb-4">Since this dashboard is shared, you can also embed it on your website.</p>

        <div x-data class="clipboard-copy mb-4">
          <pre
            x-ref="content"
            hx-boost="false"
            target="_blank"
            rel="noreferrer noopener"
          >
            &lt;iframe src="{{ dashboard.public_url }}" frameborder="0" style="position:width:100%;height:100%;"&gt;&lt;/iframe&gt;
          </pre>

          <button type="button"
            @click="navigator.clipboard.writeText($refs.content.innerText)">
            <i class="fa fa-clipboard"></i>
          </button>
        </div>
      </div>
    {% endif %}
  </div>
</section>

apps/dashboards/templates/dashboards/version_name.html
<form
  hx-post="{% url 'dashboards:version-rename' object.id %}"
  hx-trigger="submit,focusout" hx-target="this" hx-swap="outerHTML"
>
  {% csrf_token %}

  <input
    class="input__inline input__font-inherit input__ellipsis"
    id="name"
    type="text"
    name="name"
    {% if object.name != None %}
      value="{{ object.name }}"
    {% endif %}
    placeholder="{{ placeholder }}"
  />
</form>